'''
Script generated by opencode/glm5.2.
Watch the current folder for newly landed <X>.mp4 videos
and compress each of them into a new subfolder <X>/<X>.mp4,
the structure expected by FrameSense.
Videos whose compressed copy already exists are skipped,
so the script can be interrupted and restarted safely.
'''

# Script created by opencode:e-research/arc:apex
# Prompt summary: new script watching the current folder that compresses every
# new <X>.mp4 into <X>/<X>.mp4, adapting the ffmpeg-on-singularity compression command.

import subprocess
import time
from pathlib import Path
from typing import Dict, List, Tuple

WATCH_DIR = Path('.')
VIDEO_EXT = '.mp4'
SIF_PATH = '/scratch/users/k1217897/prj/framesense/singularity/extract_sound_ffmpeg.sif'
VIDEO_CODEC = 'libx264'
CRF = '23'
AUDIO_CODEC = 'aac'
DATA_MOUNT = '/data'    # bind-mount destination of the watched folder inside the container
TMP_SUFFIX = '.tmp'     # suffix of the in-progress compressed file, renamed on completion
POLL_INTERVAL = 2.0     # seconds between two scans of the watched folder
SETTLE_SECONDS = 10.0   # a video counts as fully landed once its size stayed unchanged this long


def list_videos() -> List[Path]:
    '''Return the mp4 files currently sitting in the watched folder.'''
    ret = sorted(
        p for p in WATCH_DIR.iterdir()
        if p.is_file() and p.suffix == VIDEO_EXT and not p.name.startswith('.')
    )
    return ret


def target_path(video: Path) -> Path:
    '''Return the path of the compressed copy of video, in subfolder <X>.'''
    ret = video.parent / video.stem / video.name
    return ret


def is_landed(video: Path, pending: Dict[str, Tuple[int, float]]) -> bool:
    '''Track video growth in pending and return True once its size
    stayed unchanged for SETTLE_SECONDS.'''
    ret = False
    size = video.stat().st_size
    now = time.time()
    prev_size, first_seen = pending.get(video.name, (None, now))
    if size != prev_size:
        pending[video.name] = (size, now)
    elif now - first_seen >= SETTLE_SECONDS:
        del pending[video.name]
        ret = True
    return ret


def compress(video: Path, target: Path) -> None:
    '''Compress video into target with ffmpeg inside the singularity image,
    writing to a temporary file first, renamed to target on success.'''
    target.parent.mkdir(exist_ok=True)
    tmp_name = f'{video.stem}{TMP_SUFFIX}{VIDEO_EXT}'
    cmd = [
        'singularity', 'exec', '--bind', f'{WATCH_DIR.resolve()}:{DATA_MOUNT}', SIF_PATH,
        'ffmpeg', '-y',
        '-i', f'{DATA_MOUNT}/{video.name}',
        '-c:v', VIDEO_CODEC, '-crf', CRF, '-c:a', AUDIO_CODEC,
        f'{DATA_MOUNT}/{video.stem}/{tmp_name}',
    ]
    subprocess.run(cmd, check=True)
    (target.parent / tmp_name).rename(target)


def process(video: Path) -> None:
    '''Compress video and report the outcome.'''
    print(f'Compressing {video.name} -> {target_path(video)}', flush=True)
    try:
        compress(video, target_path(video))
        print(f'OK {video.name}', flush=True)
    except (OSError, subprocess.SubprocessError) as err:
        print(f'FAILED {video.name}: {err}', flush=True)


def main() -> None:
    done = set()    # names of videos already compressed or skipped
    pending = {}    # name -> (size, time when that size was first seen)

    print(f'Watching {WATCH_DIR.resolve()} for new {VIDEO_EXT} files, compressing with {SIF_PATH}', flush=True)
    while True:
        for video in list_videos():
            if video.name in done or target_path(video).exists():
                done.add(video.name)
                continue
            try:
                landed = is_landed(video, pending)
            except OSError:
                pending.pop(video.name, None)
                continue
            if landed:
                process(video)
                done.add(video.name)
        time.sleep(POLL_INTERVAL)


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print('Stopped', flush=True)
