# Code generated by Google Gemini (20/03/2026) from the following prompt
'''
Write a python script that generates a markdown file from a json array of audio descriptions and the path to a mp4 video file the descriptions relate to. The audio descriptions have this format:

```json
[
    {
        "sentence": "The video opens with a yellow screen, followed by a blue screen with the text 'J. McMillan presents' and 'By the Waters'.",
        "start_time": "00:00"
    },
    {
        "sentence": "The scene transitions to a peaceful garden with a house, trees, and a winding path.",
        "start_time": "00:13"
    },
```

The generated markdown file should contain a table with one row per description and with three columns:
* start_time
* sentence
* sample frame

Where sample frame is an image of a frame extracted from the video file at (<start_time of current description> + <start_time following description>) / 2. That is, it should be the frame situated mid-way between the start time of the current and next description.
'''

import cv2
import json
import os
import re
from pathlib import Path

def time_to_seconds(time_str):
    """Converts MM:SS or HH:MM:SS to total seconds."""
    parts = list(map(int, time_str.split(':')))
    if len(parts) == 2:
        return parts[0] * 60 + parts[1]
    return parts[0] * 3600 + parts[1] * 60 + parts[2]

def load_descriptions(path):
    ret = []
    
    content = Path(path).read_text()
    json_blocks = re.findall(r"```json(.*?)```", content, re.DOTALL)

    for block in json_blocks:
        ret = json.loads(block)
        break
    
    return ret

def exit_if_not_found(path):
    if not Path(path).exists():
        print(f'ERROR: {path} not found')
        exit(1)

def create_description_report(json_path, video_path, output_md):
    exit_if_not_found(json_path)
    exit_if_not_found(video_path)

    # Load descriptions
    descriptions = load_descriptions(json_path)

    # Setup video capture
    cap = cv2.VideoCapture(video_path)
    fps = cap.get(cv2.CAP_PROP_FPS)
    total_frames = cap.get(cv2.CAP_PROP_FRAME_COUNT)
    duration = total_frames / fps
    
    # Create directory for images
    img_dir = "frames"
    if not os.path.exists(img_dir):
        os.makedirs(img_dir)

    md_lines = ["| start_time | sentence | sample frame |", "| --- | --- | --- |"]

    for i, desc in enumerate(descriptions):
        current_start = time_to_seconds(desc['start_time'])
        
        # Calculate midpoint
        if i < len(descriptions) - 1:
            next_start = time_to_seconds(descriptions[i+1]['start_time'])
            midpoint = (current_start + next_start) / 2
        else:
            midpoint = (current_start + duration) / 2

        # Extract frame at midpoint (converted to milliseconds)
        cap.set(cv2.CAP_PROP_POS_MSEC, midpoint * 1000)
        success, frame = cap.read()
        
        img_path = f"{img_dir}/frame_{i}.jpg"
        if success:
            cv2.imwrite(img_path, frame)
            frame_cell = f"![Frame at {midpoint}s]({img_path})"
        else:
            frame_cell = "Frame Error"

        md_lines.append(f"| {desc['start_time']} | {desc['sentence']} | {frame_cell} |")

    cap.release()

    # Write to Markdown file
    with open(output_md, 'w') as f:
        f.write("\n".join(md_lines))

if __name__ == "__main__":
    # Ensure you have 'opencv-python' installed: pip install opencv-python
    input_file = 'qwen3-32b-prompt6'
    create_description_report(f'../video/out/{input_file}.md', '../data/waves.mp4', f'{input_file}.md')
